### ISSUE TITLE
Error message Cannot find module '../build/Release/spellchecker.node'

### ISSUE THREAD

**Issue by zoechi** [nodaguti/textlint-rule-spellchecker#58]
```
Suspicious state from syntax checker textlint: Flycheck checker textlint returned 1, but its output contained no errors: ✖ Error
Cannot find module '../build/Release/spellchecker.node'
Require stack:
- /home/user/.nvm/versions/node/v12.16.2/lib/node_modules/textlint-rule-spellchecker/node_modules/spellchecker/lib/spellchecker.js
- /home/user/.nvm/versions/node/v12.16.2/lib/node_modules/textlint-rule-spellchecker/lib/spellchecker.js
- /home/user/.nvm/versions/node/v12.16.2/lib/node_modules/textlint/lib/textlint/src/engine/textlint-module-loader.js
- /home/user/.nvm/versions/node/v12.16.2/lib/node_modules/textlint/lib/textlint/src/engine/textlint-engine-core.js
- /home/user/.nvm/versions/node/v12.16.2/lib/node_modules/textlint/lib/textlint/src/textlint-engine.js
- /home/user/.nvm/versions/node/v12.16.2/lib/node_modules/textlint/lib/textlint/src/cli.js
- /home/user/.nvm/versions/node/v12.16.2/lib/node_modules/textlint/bin/textlint.js

✖ Stack trace
Error: Cannot find module '../build/Release/spellchecker.node'
Require stack:
- /home/user/.nvm/versions/node/v12.16.2/lib/node_modules/textlint-rule-spellchecker/node_modules/spellchecker/lib/spellchecker.js
- /home/user/.nvm/versions/node/v12.16.2/lib/node_modules/textlint-rule-spellchecker/lib/spellchecker.js
- /home/user/.nvm/versions/node/v12.16.2/lib/node_modules/textlint/lib/textlint/src/engine/textlint-module-loader.js
- /home/user/.nvm/versions/node/v12.16.2/lib/node_modules/textlint/lib/textlint/src/engine/textlint-engine-core.js
- /home/user/.nvm/versions/node/v12.16.2/lib/node_modules/textlint/lib/textlint/src/textlint-engine.js
- /home/user/.nvm/versions/node/v12.16.2/lib/node_modules/textlint/lib/textlint/src/cli.js
- /home/user/.nvm/versions/node/v12.16.2/lib/node_modules/textlint/bin/textlint.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:980:15)
    at Function.Module._load (internal/modules/cjs/loader.js:862:27)
    at Module.require (internal/modules/cjs/loader.js:1042:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/home/user/.nvm/versions/node/v12.16.2/lib/node_modules/textlint-rule-spellchecker/node_modules/spellchecker/lib/spellchecker.js:3:16)
    at Module._compile (internal/modules/cjs/loader.js:1156:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Module.require (internal/modules/cjs/loader.js:1042:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/home/user/.nvm/versions/node/v12.16.2/lib/node_modules/textlint-rule-spellchecker/lib/spellchecker.js:9:21)
    at Module._compile (internal/modules/cjs/loader.js:1156:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)

Try installing a more recent version of textlint, and please open a bug report if the issue persists in the latest release.  Thanks!
```

Do I need to install `spellchecker` or other dependencies from npm individually? (I tried but that failed - probably https://github.com/atom/node-spellchecker/issues/111)

**Comment by alik604** [comment]
too bad there is no support on this. I have the same issue

**Comment by rjhilgefort** [comment]
I've had this issue intermittently as well. @alik604 or @zoechi did you find any work arounds?

**Comment by future-mine** [comment]
Did anyone find a solution? It used to work in a local environment but after deploying to AWS elastic beanstalk, it throws the error. Does anyone have an idea?
![image](https://user-images.githubusercontent.com/59634187/116928223-1178d680-ac5d-11eb-80fb-7f85b3093c6f.png)
